/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agreementSol from "./Agreement.sol";
export type { agreementSol };
export type { AgreementFactory } from "./AgreementFactory";
export type { FixedRateAgreement } from "./FixedRateAgreement";
export type { Lock } from "./Lock";
export type { PayAsYouGoAgreement } from "./PayAsYouGoAgreement";
export type { Xalary } from "./Xalary";
export * as factories from "./factories";
export type { Agreement } from "./Agreement.sol/Agreement";
export { Agreement__factory } from "./factories/Agreement.sol/Agreement__factory";
export type { IERC20 } from "./Agreement.sol/IERC20";
export { IERC20__factory } from "./factories/Agreement.sol/IERC20__factory";
export { AgreementFactory__factory } from "./factories/AgreementFactory__factory";
export { FixedRateAgreement__factory } from "./factories/FixedRateAgreement__factory";
export { Lock__factory } from "./factories/Lock__factory";
export { PayAsYouGoAgreement__factory } from "./factories/PayAsYouGoAgreement__factory";
export { Xalary__factory } from "./factories/Xalary__factory";
